In [10]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

In [11]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

In [13]:
# Opening the homepage of make my trip
url = "https://www.makemytrip.com/flight/search?itinerary=DEL-BLR-14/10/2021&tripType=O&paxType=A-1_C-0_I-0&intl=false&cabinClass=E&ccde=IN&lang=eng"
driver.get(url)

time.sleep(2)

In [14]:
Flight_Price= {}
Flight_Price['Airline'] = []
Flight_Price['Source'] = []
Flight_Price['Destination'] = []
Flight_Price['Dep_Time'] = []
Flight_Price['Arrival_Time'] = []
Flight_Price['Duration'] = []
Flight_Price['Total_Stops'] = []
Flight_Price['Price'] = []

In [15]:
airLine = driver.find_elements_by_xpath("//div[@class='makeFlex simpleow']/div/div/span")
for i in airLine:
    try:
        Flight_Price['Airline'].append(i.text)
    except:
        Flight_Price['Airline'].append("-")

source = driver.find_elements_by_xpath("//div[@class='flightTimeSection flexOne timeInfoLeft']/div/p[2]")
for i in source:
    try:
        Flight_Price['Source'].append(i.text)
    except:
        Flight_Price['Source'].append("-")

destination = driver.find_elements_by_xpath("//div[@class='flightTimeSection flexOne timeInfoRight']/div/p[2]")
for i in destination :
    try:
        Flight_Price['Destination'].append(i.text)
    except:
        Flight_Price['Destination'].append("-")

total_Stops = driver.find_elements_by_xpath("//div[@class='stop-info flexOne']/div/p")
for i in total_Stops:
    try:
        Flight_Price['Total_Stops'].append(i.text)
    except:
        Flight_Price['Total_Stops'].append("-")
        
dep_time = driver.find_elements_by_xpath("//div[@class='flightTimeSection flexOne timeInfoLeft']/div/p[1]")
for i in dep_time:
    try:
        Flight_Price['Dep_Time'].append(i.text)
    except:
        Flight_Price['Dep_Time'].append("-")

arrival_time = driver.find_elements_by_xpath("//div[@class='flightTimeSection flexOne timeInfoRight']/div/p[1]")
for i in arrival_time:
    try:
        Flight_Price['Arrival_Time'].append(i.text)
    except:
        Flight_Price['Arrival_Time'].append("-")
        
duration = driver.find_elements_by_xpath("//div[@class='stop-info flexOne']/p")
for i in duration:
    try:
        Flight_Price['Duration'].append(i.text)
    except:
        Flight_Price['Duration'].append("-")
        
price = driver.find_elements_by_xpath("//div[@class='textRight flexOne']/p")
for i in price:
    try:
        Flight_Price['Price'].append(i.text)
    except:
        Flight_Price['Price'].append("-")

In [18]:
Prices_flight = pd.DataFrame(Flight_Price)
Prices_flight.to_xlsx("Flight_Price.csv")

In [45]:
Prices_flight.sample(n=5)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Price
33,IndiGo,New Delhi,Bengaluru,20:15,23:05,02 h 50 m,Non stop,"₹ 7,425"
12,Go First,New Delhi,Bengaluru,19:45,22:20,02 h 35 m,Non stop,"₹ 7,424"
28,IndiGo,New Delhi,Bengaluru,15:05,17:50,02 h 45 m,Non stop,"₹ 7,425"
11,Go First,New Delhi,Bengaluru,05:45,08:20,02 h 35 m,Non stop,"₹ 7,424"
34,Vistara,New Delhi,Bengaluru,20:40,23:20,02 h 40 m,Non stop,"₹ 7,425"